#!/usr/bin/env python3
"""Create models/iris_lidar: ArduPilot's iris_with_ardupilot drone plus a 360 deg 2D LiDAR on top,
built on models/iris_standoffs_5in (Iris flight physics, 35 cm collision footprint like our real drone).

The LiDAR mimics an LDRobot LD19: 10 Hz, 450 points per turn, 0.05-12 m range, ~1 cm noise.
It publishes on the Gazebo topic `scan` (bridged to the ROS topic /scan by sim_up.sh).

Usage:  python3 make_iris_lidar.py
"""
from pathlib import Path

SRC = Path.home() / "ardupilot_gazebo/models/iris_with_ardupilot/model.sdf"
OUT = Path(__file__).parent / "models/iris_lidar"

LIDAR_Z = 0.26  # metres above the model origin: just above the props (~0.22), so they don't block the scan

LIDAR = f"""
    <!-- ===== AirMouse: 360 deg 2D LiDAR (LD19-like) ===== -->
    <link name="lidar_link">
      <pose>0 0 {LIDAR_Z} 0 0 0</pose>
      <inertial>
        <mass>0.045</mass>
        <inertia><ixx>1e-5</ixx><iyy>1e-5</iyy><izz>1e-5</izz><ixy>0</ixy><ixz>0</ixz><iyz>0</iyz></inertia>
      </inertial>
      <visual name="lidar_visual">
        <geometry><cylinder><radius>0.025</radius><length>0.03</length></cylinder></geometry>
        <material><ambient>0.1 0.1 0.1 1</ambient><diffuse>0.1 0.1 0.1 1</diffuse></material>
      </visual>
      <sensor name="lidar" type="gpu_lidar">
        <gz_frame_id>lidar_link</gz_frame_id>
        <topic>scan</topic>
        <update_rate>10</update_rate>
        <always_on>true</always_on>
        <visualize>true</visualize>
        <lidar>
          <scan>
            <horizontal>
              <samples>450</samples>
              <resolution>1</resolution>
              <min_angle>-3.14159</min_angle>
              <max_angle>3.14159</max_angle>
            </horizontal>
            <vertical>
              <samples>1</samples>
              <resolution>1</resolution>
              <min_angle>0</min_angle>
              <max_angle>0</max_angle>
            </vertical>
          </scan>
          <range>
            <min>0.05</min>
            <max>12.0</max>
            <resolution>0.01</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </lidar>
      </sensor>
    </link>
    <joint name="lidar_joint" type="fixed">
      <parent>iris_with_standoffs::base_link</parent>
      <child>lidar_link</child>
    </joint>
    <!-- ===== end AirMouse LiDAR ===== -->

    <!-- Ground truth for testing only: publish the model's true pose on /model/iris_lidar/pose
         (bridged to ROS by sim_up.sh) so we can measure SLAM error. The real drone has no such thing. -->
    <plugin filename="gz-sim-pose-publisher-system" name="gz::sim::systems::PosePublisher">
      <publish_model_pose>true</publish_model_pose>
      <publish_link_pose>false</publish_link_pose>
      <publish_nested_model_pose>false</publish_nested_model_pose>
      <use_pose_vector_msg>false</use_pose_vector_msg>
      <update_frequency>20</update_frequency>
    </plugin>

"""

CONFIG = """<?xml version="1.0"?>
<model>
  <name>Iris with LiDAR (AirMouse)</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <description>iris_with_ardupilot plus a 360 deg 2D LiDAR. Generated by make_iris_lidar.py.</description>
</model>
"""


FRAME_SRC = Path.home() / "ardupilot_gazebo/models/iris_with_standoffs/model.sdf"
FRAME_OUT = Path(__file__).parent / "models/iris_standoffs_5in"
FOOTPRINT = 0.35  # m: our real 5-inch drone with prop guards (the Iris is ~0.64 m wide with its props)

FRAME_CONFIG = """<?xml version="1.0"?>
<model>
  <name>Iris frame, 5-inch collision footprint (AirMouse)</name>
  <version>1.0</version>
  <sdf version="1.9">model.sdf</sdf>
  <description>iris_with_standoffs with the same flight physics but collision shapes shrunk to a
    35 cm footprint (a 5-inch quad with guards). Generated by make_iris_lidar.py.</description>
</model>
"""


def make_small_frame():
    """Copy of the Iris frame: identical mass/inertia/motors (so ArduPilot's tuning still fits),
    but it only COLLIDES like our 35 cm drone. Otherwise the 64 cm Iris has ~15 cm clearance per side
    in a 1 m corridor and crashes where the real drone (~33 cm clearance) would not."""
    import re
    sdf = FRAME_SRC.read_text()
    half = FOOTPRINT / 2
    # body: replace the collision mesh (arms out to the motors) with a footprint-sized box
    sdf = re.sub(r"(<collision name='base_collision'>.*?<geometry>).*?(</geometry>)",
                 rf"\1<box><size>{FOOTPRINT} {FOOTPRINT} 0.08</size></box>\2", sdf, count=1, flags=re.S)
    # rotor discs: no collision (the guards are inside the footprint box)
    sdf = re.sub(r"\s*<collision name='collision'>.*?</collision>", "", sdf, flags=re.S)
    # landing legs: pull in under the footprint
    leg = half - 0.05
    for old, sign in {"0.123 0.22": (1, 1), "0.123 -0.22": (1, -1),
                      "-0.140 0.21": (-1, 1), "-0.140 -0.21": (-1, -1)}.items():
        sdf = sdf.replace(f"<pose>{old} -0.11", f"<pose>{sign[0] * leg:.3f} {sign[1] * leg:.3f} -0.11")
    FRAME_OUT.mkdir(parents=True, exist_ok=True)
    (FRAME_OUT / "model.sdf").write_text(sdf)
    (FRAME_OUT / "model.config").write_text(FRAME_CONFIG)
    print(f"wrote {FRAME_OUT}/model.sdf ({FOOTPRINT * 100:.0f} cm collision footprint)")


def main():
    make_small_frame()
    sdf = SRC.read_text()
    sdf = sdf.replace('<model name="iris_with_ardupilot">', '<model name="iris_lidar">', 1)
    # use the small-footprint frame (its inner model name stays iris_with_standoffs, so plugins still match)
    sdf = sdf.replace("<uri>model://iris_with_standoffs</uri>", "<uri>model://iris_standoffs_5in</uri>")
    first_plugin = sdf.index("<plugin")
    # insert before the first plugin, at the start of that line
    line_start = sdf.rfind("\n", 0, first_plugin) + 1
    sdf = sdf[:line_start] + LIDAR + sdf[line_start:]

    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "model.sdf").write_text(sdf)
    (OUT / "model.config").write_text(CONFIG)
    print(f"wrote {OUT}/model.sdf")


if __name__ == "__main__":
    main()
